# Auto-generated by NSO IDE
from typing import Protocol

from .yang.srv_l3vpn import Srv_l3vpnModule
from .yang.srv_l3vpn import *  # noqa: F401,F403

class Root(Protocol):
    srv_l3vpn: Srv_l3vpnModule
    srv_l3vpn: Srv_l3vpnList_2879b2ac
    srv_l3vpn__servicepoint__srv_l3vpn_servicepoint: Srv_l3vpnEntry_ce96e39d
    srv_l3vpn__srv_l3vpn: Srv_l3vpnList_2879b2ac
    srv_l3vpn__srv_l3vpn__list: Srv_l3vpnList_2879b2ac

root: Root

servicepoint_srv_l3vpn_servicepoint = Srv_l3vpnEntry_ce96e39d

